---
- hosts: all
  #remote_user: vagrant
  become: yes
  gather_facts: false

  vars:
    packages: ['git','tree']
    services: 
      - lorax-composer
    template: rhel8-base
    blueprints_base: /var/www/html/rhel-builds
    blueprints_dir: /var/www/html/rhel-builds/templates/
    images_dir: /var/www/html/images/
    gitrepo: https://github.com/ffirg/rhel-builds
    branch: dev
    providers:
      azure:
        image_format: vhd
      amazon:
        image_format: ami

  tasks:

    - name: Check we have a provider target...
      fail: msg="Please set the cloud variable to something supported using -e"
      when: ( cloud | length == 0 ) or ( cloud is not defined ) or ( cloud not in providers.keys() )
      tags: [ preflight ]

    - name: Ensure we have the necessary software
      dnf:
        name: "{{ packages }}"
        state: latest
      tags: [ software ]

    - name: Ensure services are running
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      tags: [ config ]

    - name: Get the latest OS image build template
      git:
        repo: "{{ gitrepo }}"
        version: "{{ branch }}"
        dest: "{{ blueprints_base}}"
        force: yes
        update: yes
      tags: [ git ]

    - name: Push the image build template
      shell: 
        cmd: composer-cli blueprints push {{ template }}.toml
        chdir: "{{ blueprints_dir}}"
      tags: [ osbuild ]

    - name: Sanity check the image build template
      shell: 
        cmd: composer-cli blueprints depsolve {{ template }}
        chdir: "{{ blueprints_dir}}"
      tags: [ osbuild ]

    - name: Kickoff the OS image build process
      shell: 
        #cmd: composer-cli compose start {{ template }} {{ providers['%s_image_format' | format(cloud)] }}
        cmd: composer-cli compose start {{ template }} {{ providers[cloud].image_format }}
        chdir: "{{ blueprints_dir}}"
      register: build_output
      tags: [ osbuild ]

    - name: Get image build UUID
      # match against --- Compose 26773968-0f61-4211-b012-f60b98c1a90c added to the queue
      set_fact: 
        uuid: "{{ build_output.stdout | regex_search('^Compose[ ](\\w+[-]\\w+[-]\\w+[-]\\w+[-]\\w+)[ ]added[ ]to[ ]the[ ]queue$', '\\1') | first }}"
      tags: [ osbuild ]

    - debug: 
        msg: Image builder UUID is {{ uuid }}
      when: uuid is defined
      tags: [ osbuild ]

    - name: Check image build progress
      # returns something like --- f1feb7a3-056c-4d8c-a446-baa2af7c2e78 FINISHED|FAILED|RUNNING|WAITING rhel8-base 0.1.1 vhd
      shell:
        cmd: composer-cli compose list | grep {{ uuid }}
        chdir: "{{ blueprints_dir}}"
      register: build_status
      until: build_status.stdout.find("FINISHED") != -1
      retries: 20
      delay: 30
      tags: [ osbuild ]

    - name: Setup images output directory
      file:
        path: "{{ images_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: '0750'

    - name: Save OS Image
      shell:
        cmd: composer-cli compose image {{ uuid }}
        chdir: "{{ images_dir}}"
      tags: [ osbuild ]

