---
- hosts: localhost
  gather_facts: false

  vars:
    rg_name: rhel-images
    location: uksouth
    storage_name: rhelbuilds

  tasks:

    - name: Create Azure Resource Group
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"
        tags:
          os: RHEL
          infratype: images
      tags: [ 'azure', 'rg' ]

    - name: Create Azure Storage Account
      azure_rm_storageaccount:
        resource_group: "{{ rg_name }}"
        name: "{{ storage_name }}"
        type: Standard_GRS
        access_tier: Cool
        kind: BlobStorage
        tags:
          os: RHEL
          infratype: images
      tags: [ 'azure', 'storage' ]

    - name: Upload OS Build Image
      azure_rm_storageblob:
        resource_group: "{{ rg_name }}"
        storage_account_name: "{{ storage_name }}"
        container: goldbuilds
        state: present
        blob: {{ uuid }}
        src: "{{ images_dir }}{{ uuid }}-disk.{{ providers[cloud].image_format }}"
        tags:
          os: RHEL
          infratype: images
      tags: [ 'azure', 'image' ]

