---
- hosts: all
  remote_user: vagrant
  become: yes
  gather_facts: false

  vars:
    packages: ['dnf-utils', 'createrepo_c', 'composer-cli', 'lorax-composer', 'httpd', 'git', 'cockpit', 'cockpit-composer']
    services: 
      - httpd
      - osbuild-composer
      - cockpit.socket
    repos:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms

  tasks:
    - name: Ensure RHSM repositories are available
      rhsm_repository:
        name: '{{ item }}'
        state: enabled
      loop: "{{ repos }}"
      tags: [ software ]

    - name: Install RPMs
      dnf:
        name: "{{ packages }}"
        state: latest
      tags: [ software ]

    - name: Change SELinux for composer
      selinux:
        policy: targeted
        state: permissive
      tags: [ config ]

    - name: Start Services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      tags: [ config ]

    - name: Sync RHEL8 repos to host
      shell: reposync -n -p /var/www/html --repoid "{{ item }}" --downloadcomps --download-metadata
      loop: "{{ repos }}"
      tags: [ sync ]

    - name: Composer tells us to disable all RHSM repositories
      rhsm_repository:
        name: '*'
        state: disabled
      tags: [ rhsm ]

    - name: Create local RHEL8 repos on host
      shell: createrepo -v /var/www/html/{{ item }}/ -g $(ls /var/www/html/{{ item }}/repodata/*comps.xml)
      loop: "{{ repos }}"
      tags: [ repos ]

    - name: Create Repos Definition from Template
      template:
        src: osbuilds.repo.j2
        dest: /etc/yum.repos.d/osbuilds.repo
        owner: root
        group: root
        mode: '0644'
      tags: [ rhsm ]

