---
- hosts: all
  #remote_user: vagrant
  become: yes
  gather_facts: false

  vars:
    packages: ['git','tree']
    services: 
      - lorax-composer
    user: root
    group: root
    template: rhel8-base
    blueprints_base: /var/www/html/rhel-builds
    blueprints_dir: /var/www/html/rhel-builds/templates/
    images_dir: /var/www/html/images
    gitrepo: https://github.com/ffirg/rhel-builds
    branch: dev
    providers:
      azure:
        image_format: vhd
      amazon:
        image_format: ami
    
    uuid: foo

  tasks:

    - name: Retrieve OS Image from build server
      synchronize:
        src: "{{ images_dir }}/{{ uuid }}-disk.{{ providers[cloud].image_format }}"
        dest: "rsync://towerhost/{{ images_dir }}/"
      tags: [ 'osbuild' , 'retrieve' ]
