name = "rhel8-base"
description = "RHEL8 Golden Cloud Image"
version = "0.1.0"
modules = []
groups = []

[[packages]]
name = "rpm"
version = "*"

[customizations]
hostname = "_newbuild8_"

[[customizations.group]]
name = "automation"
gid = 11111

[[customizations.user]]
name = "automation"
description = "Automation User"
home = "/home/automation/"
shell = "/usr/bin/bash"
groups = ["wheel"]
uid = 11111
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFDgRlsLpArnXtjSMUMb8fVQ71zsP2g7EO3zfx5Nm+9JPJoN4428SM/AXkJiwnw3nEUNcqehpbq8mhrWmZud5LSCLwKjhF2B8awKei9K5Qfmp/QWlJ1FIuR3y/MbxNpEhYuTEeJRyLzQTxtxbt7oAIq9yZ2nk7eYSH5Alj6N03PtxNLzwxRt2IoPS80LFPd0ZXm9K5uWhUCw8MvxMQWUrze/Xh778NjRBxL7HBXIxYIG7k2VuliF6aEM+PSM7N5lrz7g5mSBSqx/kjR4FgnOvwg9etzp7qnGUyJe2JNitUbt/vZu8XSZqa4tbCeoFE8TRh8/F52B+5Tp1R53XzzFcuYLBYdNLNRWp/fUf3VIuNkI/7yuPCfQN0DE1xd83RD9X1XVT6oHLaUF3Nry3IHAs6/WpHlxoBmSbVykJNHqHHNASSnUiwQae47nuATTPHQ/Ski9Kt1NL7H74w3XMMNR2QGpF4KUzi3ZEmNpRCVk8kCJnmM+Ud/XZGED23PHXf9e8= Automation User"
